### PR TITLE
a better implementation of MultidimensionalSort

### PR DESCRIPTION
**Pull request by UniverseObserver**
I wrote a more elegent implementation of Exercise 21 MultidimensionalSort in Chapter 2, Section 5, Page 365

### CODE REVIEW

**Comment by reneargento** [comment]
Thank you for the contribution!
There are some keywords such as `var` and `breakpoints`, which don’t compile in Java, so I assume it has been initially written on another language.  But other than that, the implementation looks good.
I have merged the PR and will update the code to compile correctly.

**Comment by UniverseObserver** [comment]
Sorry for ths inconvinence, I was using Java 11.

**Comment by reneargento** [comment]
I see, so it makes sense, I wasn't aware that it is available in Java 11.
Thanks!

**Comment by UniverseObserver** [comment]
Also, breakpoints is a variable that is supposed to be deleted but I forget
to do so. It would be great if you detele those several lines with this
variable.

**Comment by reneargento** [comment]
I deleted it and did some minor changes here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/745f3ecb2355f3c9684ef213417ad03250c896a3
The main idea and algorithm remains the same.

**Comment by UniverseObserver** [comment]
Thank you very much!

**Pull request merged**
