### PR TITLE
Update exercise6.txt

### PR DESCRIPTION
**Pull request by Oreshnik**
More trees for N = 9 and N = 10
If you are not agree that there is 3 structurally different 2-3 trees for N=9, anyway there is a misprint:
instead of 2 / 7 = 0.71 should be 5 / 7 = 0.71
instead of 5 / 7 = 0.29 should be 2 / 7 = 0.29

### CODE REVIEW

**Comment by reneargento** [comment]
The exercise tells us to ignore the order of the subtrees, so I would consider both
```
      ()
   ()    ()
( ) ( ) () ()
```
and
```
      ()
   ()    ()
( ) () ( ) ()
```
to be the same because they are on the same level. But I agree that the definition of `structurally different` is a bit subjective.

The probability was inverted indeed, I fixed it on: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/12d744a8c96a2db151249fc90dfbd2afd267bf41
Thanks!

**Comment by Oreshnik** [comment]
I see. On my part I considered that a subtree is a tree with the root from any node in the tree. From this point of view there are definitely three different type of subtree from second level in two trees:

a) ( ) 5n       ( ) 3n         b)  ( ) 4n*2  
(   ) (   )      ( ) ( )              (   ) ( )

**Comment by reneargento** [comment]
Ok, it makes sense to see the subtrees that way.
Only one detail: due to the way rotations work, it looks to be impossible to arrive at one of the trees you mentioned (going from N = 8 to N = 9):
```
      ()
   ()    ()
( ) () ( ) ()
```
The following tree is possible though:
```
      ()
   ()    ()
( ) () () ( )
```
I updated the exercise here with the other structures: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d7570a8943c898f46d9535c8ae0f999eaeafc402

**Comment by Oreshnik** [comment]
Great, thank you!

**Pull request closed without merging**
